apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"db.smartx.com/v1alpha1","kind":"MongoCluster","metadata":{"name":"example-mongocluster"},"spec":{"mongo":{"bindIp":"0.0.0.0","image":"mongo:4.0.11","imagePullPolicy":"IfNotPresent","noprealloc":true,"replSet":"zbs","replicas":3,"resources":{"requests":{"cpu":"1","memory":"2Gi"}},"smallfiles":true,"storage":{"resources":{"requests":{"storage":"25Gi"}},"storageClassName":"mongo-disks"},"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}],"wiredTigerCacheSize":"0.25"}},"status":{}}]'
    capabilities: Basic Install
  name: mongo-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: MongoCluster
      name: mongoclusters.db.smartx.com
      version: v1alpha1
  description: Placeholder description
  displayName: Mongo Operator
  install:
    spec:
      deployments:
      - name: mongo-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: mongo-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: mongo-operator
            spec:
              containers:
              - command:
                - mongo-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: mongo-operator
                image: 192.168.27.146/mongo-operator:v0.0.4
                imagePullPolicy: Always
                name: mongo-operator
                resources: {}
              serviceAccountName: mongo-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - mongo-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - db.smartx.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: mongo-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.2
