apiVersion: db.smartx.com/v1alpha1
kind: MongoCluster
metadata:
  name: example-mongocluster
spec:
  # Add fields here
  mongo:
    # image: mongo:2.6.12  # if change to 2.6.12, fix command to older version.
    image: mongo:4.0.11
    imagePullPolicy: IfNotPresent
    replicas: 3  # TODO(vici) TOBE DEPRECATED
    replSet: zbs
    wiredTigerCacheSize: "0.25"
    bindIp: 0.0.0.0
    smallfiles: true
    noprealloc: true
#    command:
#      - mongod
#      - "--wiredTigerCacheSizeGB"
#      - "0.25"
#      - "--bind_ip"
#      - "0.0.0.0"
#      - "--smallfiles"
#      - "--noprealloc"
#      - "--replSet"
#      - "rs0"
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
    storage:
      storageClassName: fast-disks # specify the local pv or other pvc gens.
      resources:
        requests:
          storage: 25Gi
    tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

status: {}
