apiVersion: db.smartx.com/v1alpha1
kind: MongoCluster
metadata:
  name: example-mongocluster
spec:
  # Add fields here
  mongo:
    # image: mongo:2.6.12  # if change to 2.6.12, fix command to older version.
    image: mongo:4.0.11
    imagePullPolicy: IfNotPresent
    replicas: 3  # TODO(vici) TOBE DEPRECATED
    replSet: zbs
    wiredTigerCacheSize: "0.25"
    bindIp: 0.0.0.0
    smallfiles: true
    noprealloc: true
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      # limit
    storage:
      storageClassName: mongo-disks
      resources:
        requests:
          storage: 25Gi
    tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

status: {}
