apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-operator
  template:
    metadata:
      labels:
        name: mongo-operator
    spec:
      serviceAccountName: mongo-operator
      containers:
        - name: mongo-operator
          # Replace this with the built image name
          image: dockerhub.smartx.com/mongo-operator:v0.01
          command:
          - mongo-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mongo-operator"
